export default {
   "productibles":{
      "Lancer":{
         "production_charge":3,
         "cost":{
            "Wood":{
               "symbol":"W",
               "name":"Wood",
               "value":5
            },
            "Stone":{
               "symbol":"S",
               "name":"Stone",
               "value":2
            },
            "Food":{
               "symbol":"F",
               "name":"Food",
               "value":5
            }
         },
         "id":"6a8640d8-d4ea-4a66-a201-9ba04860c504",
         "move_speed":10,
         "destination":null,
         "pv":20,
         "attack":10,
         "defense":5,
         "weapon":{
            "accuracy":85,
            "critic_chance":6,
            "critic_factor":0.5,
            "damage":8,
            "kind":"PERFORATING",
            "factor_kind":0.3
         }
      },
      "Epeist":{
         "production_charge":3,
         "cost":{
            "Wood":{
               "symbol":"W",
               "name":"Wood",
               "value":2
            },
            "Stone":{
               "symbol":"S",
               "name":"Stone",
               "value":5
            },
            "Food":{
               "symbol":"F",
               "name":"Food",
               "value":5
            }
         },
         "id":"11e9359d-b92a-4d6e-881f-e098ae59c71a",
         "move_speed":10,
         "destination":null,
         "pv":25,
         "attack":8,
         "defense":4,
         "weapon":{
            "accuracy":85,
            "critic_chance":10,
            "critic_factor":0.2,
            "damage":12,
            "kind":"CUTTING",
            "factor_kind":0.4
         }
      },
      "Barbarian":{
         "production_charge":3,
         "cost":{
            "Wood":{
               "symbol":"W",
               "name":"Wood",
               "value":3
            },
            "Stone":{
               "symbol":"S",
               "name":"Stone",
               "value":4
            },
            "Food":{
               "symbol":"F",
               "name":"Food",
               "value":4
            }
         },
         "id":"e6bd6b61-9d1b-4739-ab30-dc665e46427e",
         "move_speed":8,
         "destination":null,
         "pv":30,
         "attack":15,
         "defense":5,
         "weapon":{
            "accuracy":90,
            "critic_chance":5,
            "critic_factor":0.5,
            "damage":10,
            "kind":"CONTENDING",
            "factor_kind":0.2
         }
      },
      "Scout":{
         "production_charge":3,
         "cost":{
            "Wood":{
               "symbol":"W",
               "name":"Wood",
               "value":2
            },
            "Stone":{
               "symbol":"S",
               "name":"Stone",
               "value":0
            },
            "Food":{
               "symbol":"F",
               "name":"Food",
               "value":4
            }
         },
         "id":"eac65e68-c7fc-4679-8e6e-594d4efd55ce",
         "move_speed":12,
         "destination":null,
         "pv":10,
         "attack":10,
         "defense":2,
         "weapon":{
            "accuracy":85,
            "critic_chance":10,
            "critic_factor":0.2,
            "damage":12,
            "kind":"CUTTING",
            "factor_kind":0.4
         }
      },
      "Farmer":{
         "production_charge":1,
         "cost":{
            "Wood":{
               "symbol":"W",
               "name":"Wood",
               "value":1
            },
            "Stone":{
               "symbol":"S",
               "name":"Stone",
               "value":1
            },
            "Food":{
               "symbol":"F",
               "name":"Food",
               "value":3
            }
         },
         "id":"7c06a71d-5a25-47c7-ab3c-d0a8495f4093",
         "move_speed":10,
         "destination":null,
         "incomes":{
            "Wood":{
               "symbol":"W",
               "name":"Wood",
               "value":1
            },
            "Stone":{
               "symbol":"S",
               "name":"Stone",
               "value":1
            },
            "Food":{
               "symbol":"F",
               "name":"Food",
               "value":3
            }
         },
         "production_value":3
      },
      "Logger":{
         "production_charge":1,
         "cost":{
            "Wood":{
               "symbol":"W",
               "name":"Wood",
               "value":1
            },
            "Stone":{
               "symbol":"S",
               "name":"Stone",
               "value":2
            },
            "Food":{
               "symbol":"F",
               "name":"Food",
               "value":3
            }
         },
         "id":"6f95e1d2-3b86-43f7-aeb7-19b1456ccf86",
         "move_speed":10,
         "destination":null,
         "incomes":{
            "Wood":{
               "symbol":"W",
               "name":"Wood",
               "value":3
            },
            "Stone":{
               "symbol":"S",
               "name":"Stone",
               "value":1
            },
            "Food":{
               "symbol":"F",
               "name":"Food",
               "value":1
            }
         },
         "production_value":3
      },
      "Digger":{
         "production_charge":1,
         "cost":{
            "Wood":{
               "symbol":"W",
               "name":"Wood",
               "value":2
            },
            "Stone":{
               "symbol":"S",
               "name":"Stone",
               "value":1
            },
            "Food":{
               "symbol":"F",
               "name":"Food",
               "value":3
            }
         },
         "id":"d2dfb00c-1604-42be-bc42-664786f84595",
         "move_speed":10,
         "destination":null,
         "incomes":{
            "Wood":{
               "symbol":"W",
               "name":"Wood",
               "value":1
            },
            "Stone":{
               "symbol":"S",
               "name":"Stone",
               "value":3
            },
            "Food":{
               "symbol":"F",
               "name":"Food",
               "value":1
            }
         },
         "production_value":3
      },
      "Builder":{
         "production_charge":3,
         "cost":{
            "Wood":{
               "symbol":"W",
               "name":"Wood",
               "value":2
            },
            "Stone":{
               "symbol":"S",
               "name":"Stone",
               "value":2
            },
            "Food":{
               "symbol":"F",
               "name":"Food",
               "value":3
            }
         },
         "id":"c317dd5c-f820-4c10-99b8-6a88b0a26b41",
         "move_speed":10,
         "destination":null,
         "incomes":{
            "Wood":{
               "symbol":"W",
               "name":"Wood",
               "value":1
            },
            "Stone":{
               "symbol":"S",
               "name":"Stone",
               "value":1
            },
            "Food":{
               "symbol":"F",
               "name":"Food",
               "value":1
            }
         },
         "production_value":3
      }
   },
   "buildables":{
      "Farm":{
         "production_charge":10,
         "cost":{
            "Stone":{
               "symbol":"S",
               "name":"Stone",
               "value":1
            },
            "Food":{
               "symbol":"F",
               "name":"Food",
               "value":4
            }
         },
         "name":"Farm",
         "incomes":{
            "Food":{
               "symbol":"F",
               "name":"Food",
               "value":3
            }
         },
         "move_speed":0,
         "bonus_attack":0,
         "bonus_defense":1,
         "productibles":[
            
         ],
         "production_value":1,
         "production_queue":[
            
         ],
         "production_current":null,
         "can_see_in":true,
         "can_see_behind":true,
         "bonus_vision":0,
         "bonus_retrait":0
      },
      "Capital":{
         "production_charge":100,
         "cost":{
            "Stone":{
               "symbol":"S",
               "name":"Stone",
               "value":50
            },
            "Wood":{
               "symbol":"S",
               "name":"Stone",
               "value":50
            },
            "Food":{
               "symbol":"F",
               "name":"Food",
               "value":50
            }
         },
         "name":"Capital",
         "incomes":{
            "Food":{
               "symbol":"F",
               "name":"Food",
               "value":5
            },
            "Wood":{
               "symbol":"W",
               "name":"Wood",
               "value":1
            }
         },
         "move_speed":0,
         "bonus_attack":-10,
         "bonus_defense":10,
         "productibles":[
            "Farmer",
            "Logger",
            "Digger",
            "Builder",
            "Scout"
         ],
         "production_value":2,
         "production_queue":[
            
         ],
         "production_current":null,
         "can_see_in":true,
         "can_see_behind":true,
         "bonus_vision":0,
         "bonus_retrait":0
      }
   }
}